name: elkjs publish dev

on:  
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    # Checkout elkjs itself
    - uses: actions/checkout@v1
    # Additionally checkout elk
    - uses: actions/checkout@v1
      with:
        repository: eclipse/elk
        ref: master
    # GWT requires a specific jdk
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    # We want to execute gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/
    - name: npm install, build, and test
      run: |
        npm run setDevVersion
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: npm publish
      run: npm publish --dry-run
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}
